name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13.0-beta.4']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: Initialize Conda
      shell: bash
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda init bash
    - name: Create Conda environment
      shell: bash
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda create --name homegrowndhe python=${{ matrix.python-version }} -y
    - name: Activate Conda environment and install Poetry
      shell: bash
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda activate homegrowndhe
        pip install poetry
    - name: Install dependencies with Poetry
      shell: bash
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda activate homegrowndhe
        poetry install
    - name: Lint with flake8
      shell: bash
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda activate homegrowndhe
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        source ~/miniconda/etc/profile.d/conda.sh
        conda activate homegrowndhe
        poetry run pytest
