name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13.0-beta.4']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: Install Poetry and poetry2conda
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        pip install poetry2conda
    - name: Generate environment.yaml
      run: |
        poetry2conda pyproject.toml environment.yaml
    - name: Create Conda environment
      run: |
        conda env create -f environment.yaml
    - name: Activate Conda environment
      run: |
        source activate homegrowndhe
    - name: Lint with flake8
      run: |
        source activate homegrowndhe
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source activate homegrowndhe
        pytest
