name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13.0-beta.4']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yaml --name base
    - name: Activate conda environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
    - name: Install Poetry and dependencies
      run: |
        pip install poetry
        poetry add pytest
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
